//! `reverse_push` provides a gRPC-based client library for a Reverse Push architecture.
//!
//! This architecture allows hosts (agents) deployed behind firewalls or NATs to
//! establish a long-lived outbound streaming connection to a central Cloud Control Plane.
//! Once connected, the Control Plane can asynchronously "push" commands to the host,
//! completely circumventing the need for inbound open ports on the host's side.

pub mod control_plane {
    //! Autogenerated gRPC definitions from the `control_plane.proto` file.
    tonic::include_proto!("control_plane");
}

pub mod client;

pub use client::{ReversePushBuilder, ReversePushClient};
